config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :reserved_stock_items, :except => [:show, :new, :edit]
    resources :users do
      resources :reserved_stock_items do
        member do
          post :restock
        end
      end
    end

  end
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :reserved_stock_items, only: :index do
        collection do
          post :reserve
          post :restock
          post :restock_expired
        end
      end
      resources :user do
        resources :reserved_stock_items, only: :index
      end
    end
  end
end

app/models/spree/reserved_stock_item.rb
# Validates that the StockLocation is specifically for reserved stock
class ReservedStockLocationValidator < ActiveModel::Validator
  def validate(record)
    return unless record.stock_location # Missing stock location should be caught by other validator
    return if record.stock_location.reserved_items?
    record.errors[:stock_location] << "StockLocation for ReservedStockItems must have reserved_items? == true"
  end
end

# Validates that the reserved stock item is not backorderable
class NotBackOrderableValidator < ActiveModel::Validator
  def validate(record)
    return unless record.backorderable?
    record.errors[:backorderable] << "ReservedStockItems must not be backorderable"
  end
end

module Spree
  # A StockItem that's been reserved by a customer. It will be stored in a
  # dedicated StockLocation, but rmembers the original StockLocation for the
  # items, so the can be restored if the reservation expiresor is cancelled.
  class ReservedStockItem < Spree::StockItem
    include ActiveModel::Validations

    belongs_to :user, class_name: Spree::UserClassHandle.new

    belongs_to :original_stock_location, class_name: Spree::StockLocation

    # Remove 'variant_id' attribute from its existing uniqueness validator
    # (effectively disabling it) so we can add a new uniqueness validator that
    # is scoped to user_id. We want multiple users to be able to reserve the
    # same variant.
    variant_id_uniqueness_validator = validators_on(:variant_id).detect do |validator|
      validator.is_a? ActiveRecord::Validations::UniquenessValidator
    end
    variant_id_uniqueness_validator.attributes.delete(:variant_id) if variant_id_uniqueness_validator

    validates_with ReservedStockLocationValidator
    validates_with NotBackOrderableValidator
    validates_uniqueness_of :variant_id,
      scope: [
        :stock_location_id,
        :deleted_at,
        :user_id,
        :original_stock_location_id
      ]
    validates :user_id, presence: true
    validates :original_stock_location_id, presence: true
  end
end

app/controllers/spree/admin/reserved_stock_items_controller.rb
module Spree
  module Admin
    class ReservedStockItemsController < ResourceController
      before_action :load_user, only: [:index, :create, :new, :restock]
      before_action :load_variants, only: [:create, :new]
      before_action :load_original_stock_locations, only: [:create, :new]

      class_attribute :variant_display_attributes
      self.variant_display_attributes = [
        { translation_key: :sku, attr_name: :sku },
        { translation_key: :name, attr_name: :name }
      ]

      def index
        @reserved_stock_items = @user.reserved_stock_items
        @variant_display_attributes = self.class.variant_display_attributes
      end

      def create
        validator = Spree::Api::V1::Validators::ReserveStockParamsValidator.new(permitted_resource_params)

        if validator.validate
          variant = Spree::Variant.find(permitted_resource_params[:variant_id])
          original_stock_location = Spree::StockLocation.find(permitted_resource_params[:original_stock_location_id])
          @reserved_stock_item = Spree::Stock::Reserver.new(variant, @user, original_stock_location).reserve(
            variant,
            original_stock_location,
            @user,
            permitted_resource_params[:quantity].to_i,
            Time.zone.parse(permitted_resource_params[:expires_at])
          )
          flash[:success] = flash_message_for(@reserved_stock_item, :successfully_created)
          redirect_to admin_user_reserved_stock_items_path(@user)
        else
          flash[:error] = "#{Spree.t("admin.reserved_stock_item.unable_to_create")}: #{validator.errors}"
          render :new
        end
      rescue => e
        flash[:error] = "#{Spree.t("admin.reserved_stock_item.unable_to_create")}: #{e.message}"
        render :new
      end

      def restock
        variant = Spree::ReservedStockItem.find(params[:id]).variant
        Spree::Stock::Reserver.new(variant, @user, original_stock_location).restock(variant, @user)
        flash[:success] = flash_message_for(@reserved_stock_item, :successfully_restocked)
        redirect_to admin_user_reserved_stock_items_path(@user)
      rescue => e
        flash[:error] = "#{Spree.t("admin.reserved_stock_item.unable_to_restock")}: #{e.message}"
        redirect_to admin_user_reserved_stock_items_path(@user)
      end

      private

      def location_after_destroy
        :back
      end

      def location_after_save
        :back
      end

      def collection
        []
      end

      def permitted_resource_params
        params.require(:reserved_stock_item).permit!.
          merge(user_id: @user.id)
      end


      def load_user
        @user = Spree.user_class.find(params[:user_id])
      end

      def load_original_stock_locations
        @original_stock_locations = Spree::StockLocation.not_reserved_items.order_default
      end

      def load_variants
        @variants = Spree::Variant
                    .includes(option_values: :option_type)
                    .order(id: :desc)
      end
    end
  end
end

app/controllers/spree/api/v1/reserved_stock_items_controller.rb
module Spree
  module Api
    module V1
      # API Controller for reserving, restocking and expiring stock
      class ReservedStockItemsController < Spree::Api::BaseController
        before_action :authorize_reserving_stock

        rescue_from ActiveRecord::RecordNotFound, with: :not_found

        def index
          @reserved_stock_items = scope.
                                  ransack(params[:q]).
                                  result.
                                  page(params[:page]).
                                  per(params[:per_page])
          respond_with(@reserved_stock_items)
        end

        def reserve
          render_reserve_param_errors(params); return if performed?
          expires_at = params[:expires_at].present? ? Time.zone.parse(params[:expires_at]) : nil
          @reserved_stock_item = Spree::Stock::Reserver.new(variant, user, original_stock_location).reserve(
            params[:quantity].to_i,
            expires_at
          )
          if @reserved_stock_item.present?
            respond_with(@reserved_stock_item, status: :created, default_template: :show)
          else
            invalid_resource!(@reserved_stock_item)
          end
        end

        def restock
          render_restock_param_errors(params); return if performed?
          quantity = params[:quantity].present? ? params[:quantity].to_i : nil
          @reserved_stock_item = Spree::Stock::Reserver.new(variant, user, original_stock_location).restock(
            quantity
          )
          respond_with(@reserved_stock_item, status: :created, default_template: :show)
        end

        def restock_expired
          Spree::Stock::Reserver.new.restock_expired
          head 204 # return success with no body
        end

        private

        def authorize_reserving_stock
          authorize! :manage, ReservedStockItem
        end

        def user
          Spree.user_class.find(params[:user_id])
        end

        def variant
          variant_id = params[:variant_id]
          sku = params[:sku]
          return Spree::Variant.where(sku: sku).first! if sku.present?
          Spree::Variant.find(variant_id)
        end

        def original_stock_location
          Spree::StockLocation.find(params[:original_stock_location_id])
        end

        def render_reserve_param_errors(params)
          validator = Validators::ReserveStockParamsValidator.new(params)
          render_errors(validator.errors) unless validator.validate
        end

        def render_restock_param_errors(params)
          validator = Validators::RestockParamsValidator.new(params)
          render_errors(validator.errors) unless validator.validate
        end

        def render_errors(errors)
          return if errors.blank?
          Rails.logger.error errors
          render json: {'errors': errors}.to_json, status: 422
        end

        def scope
          base_scope = if params[:user_id].present?
            user
          else
            Spree::StockLocation.reserved_items_location
          end
          base_scope.reserved_stock_items.accessible_by(current_ability, :read).includes(:variant)
        end

        def not_found(error)
          @error = error
          render "spree/api/v1/reserved_stock_items/errors/entity_not_found", status: 404
        end
      end
    end
  end
end

app/helpers/spree/admin/reserved_stock_items_helper.rb
module Spree
  module Admin
    module ReservedStockItemsHelper
      def stock_location_name(stock_item)
        stock_location = stock_item.stock_location
        return stock_location.name unless stock_location.reserved_items?

        user_link = link_to(stock_item.user.email, admin_user_path(stock_item.user))
        "#{stock_location.name} (#{user_link})".html_safe
      end
    end
  end
end

app/views/spree/admin/reserved_stock_items/_form.html.erb
<div data-hook="admin_reserved_stock_item_form_fields" class="row">
  <div class="alpha omega twelve columns">
    <%= f.field_container :original_stock_location do %>
      <%= f.label :original_stock_location, Spree.t('admin.reserved_stock_item.original_stock_location') %>
      <%= f.select :original_stock_location_id, @original_stock_locations.to_a.collect{|l|[l.name.humanize, l.id]}, {include_blank: false}, {class: 'select2 fullwidth', "data-placeholder" => Spree.t('admin.reserved_stock_item.select_an_original_stock_location')} %>
      <%= f.error_message_on :original_stock_location_id %>
    <% end %>
  </div>

  <div class="alpha omega twelve columns">
    <%= f.field_container :variant_id do %>
      <%= f.label 'variant_id', Spree.t(:variant) %>
      <%= f.select :variant_id, options_from_collection_for_select(@variants, :id, :name_and_sku), {include_blank: false}, {class: 'select2 fullwidth'} %>
    <% end %>
  </div>

  <div class="alpha omega twelve columns">
    <%= f.field_container :quantity do %>
      <%= label_tag 'quantity', Spree.t(:quantity) %>
      <%= number_field_tag 'reserved_stock_item[quantity]', 1, class: 'fullwidth', id: :reserved_stock_item_quantity %>
    <% end %>
  </div>

  <div class="alpha omega twelve columns">
    <%= f.field_container :expires_at do %>
      <%= f.label :expires_at, Spree.t('admin.reserved_stock_item.expires_at') %>
      <%= f.error_message_on :expires_at %>
      <%= f.text_field :expires_at, :value => datepicker_field_value(@reserved_stock_item.expires_at), :class => 'datepicker' %>
    <% end %>
  </div>

</div>

app/views/spree/admin/reserved_stock_items/index.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:"admin.user.reserved_stock_items")} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= link_to_with_icon 'arrow-left', Spree.t("admin.reserved_stock_item.back_to_user_list"), admin_users_path, class: 'button' %>
  </li>
  <% if can?([:manage], Spree::ReservedStockItem) %>
    <li>
      <%= button_link_to Spree.t(:new_reserved_stock_item), spree.new_admin_user_reserved_stock_item_path(@user), :icon => 'plus', :id => 'admin_new_reserved_stock_item_link' %>
    </li>
  <% end %>
<% end %>


<%= render :partial => 'spree/admin/users/sidebar', :locals => { :current => :reserved_stock_items } %>

<fieldset data-hook="admin_user_reserved_stock_items" class="alpha twelve columns">
  <legend><%= Spree.t(:"admin.user.reserved_stock_items") %></legend>

  <% if @reserved_stock_items.any? %>
    <table class="stock-reserved index" id="listing_items" data-hook="stock-reserved-for-user">
      <colgroup>
        <col style="width: 40%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 5%" />
        <col style="width: 5%" />
      </colgroup>
      <thead>
        <tr>
          <th><%= Spree.t(:item) %></th>
          <th><%= Spree.t(:options) %></th>
          <th><%= Spree.t(:original_stock_location) %></th>
          <th><%= Spree.t(:expires_at) %></th>
          <th><%= Spree.t(:count_on_hand) %></th>
        </tr>
      </thead>

      <tbody>
        <% @reserved_stock_items.each do |item| %>
          <tr class="<%= cycle('odd', 'even', :name => 'stock_locations')%>" data-variant-id="<%= item.variant.id %>">
            <td class="align-center no-padding">
              <div class='variant-container'>
                <div class='variant-image'>
                  <%= image_tag(item.variant.display_image(fallback: false).attachment(:small)) %>
                </div>
                <div class='variant-details'>
                  <table class='stock-variant-field-table'>
                    <tbody>
                      <% @variant_display_attributes.each do |display_attribute| %>
                        <tr>
                          <td><%= Spree.t(display_attribute[:translation_key]) %></td>
                          <td class="fullwidth">
                            <%= item.variant.send(display_attribute[:attr_name]) %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </td>
            <td class="align-center">
              <table class='stock-variant-field-table'>
                <% item.variant.option_values.sort_by(&:option_type_name).each do |option_value| %>
                  <tr>
                    <td>
                      <%= option_value.option_type_presentation %>
                    </td>
                    <td><%= option_value.presentation %></td>
                  </tr>
                <% end %>
              </table>
            </td>
            <td class="align-center">
              <%= item.original_stock_location.name %>
            </td>
            <td class="align-center">
              <%= item.expires_at %>
            </td>
            <td class="align-center">
              <span><%= item.count_on_hand %></span>
            </td>
            <td class="actions">
              <% if can?(:manage, item) %>
                <%= link_to_with_icon('undo', Spree.t(:restock), restock_admin_user_reserved_stock_item_path(@user, item), method: :post) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alpha twelve columns no-objects-found">
      <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/reserved_stock_item')) %>
      <% if can?([:manage], Spree::ReservedStockItem) %>
        <%= link_to Spree.t("add_one"), spree.new_admin_user_reserved_stock_item_path(@user) %>!
      <% end %>
    </div>
  <% end %>
</fieldset>

app/views/spree/admin/reserved_stock_items/new.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render :partial => 'spree/admin/users/sidebar', :locals => { :current => :reserved_stock_items } %>
<% content_for :page_actions do %>
  <li>
    <%= link_to_with_icon 'arrow-left', Spree.t("admin.reserved_stock_item.back_to_reserved_stock_item_list"), admin_user_reserved_stock_items_path(@user), class: 'button' %>
  </li>
<% end %>


<%= form_for [:admin, @user, @reserved_stock_item] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t("admin.reserved_stock_item.new") %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links', :locals => { :collection_url => admin_user_reserved_stock_items_path(@user) } %>
  </fieldset>
<% end %>